name: learningdart
description: "A modern scientific calculator"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  math_expressions: ^2.4.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2  # For saving calculator history

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/neo_calc.jpeg"
  min_sdk_android: 21
